# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: 咕咚
subtitle: "Android Developer G粉 米粉<br> 保持一份初学者的心态，愿激情常在。"
email: 1252768410@qq.com
emailname: QQ Mail
name: 咕咚
description: >
  有意义就是好好活，好好活就有意义。
baseurl: / # the subpath of your site, e.g. /blog/
url: "http://bencentra.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives: 
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: gudong

# Google analytics
# ga_tracking_id: "UA-64640288-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: false                           # Include in the "Share" section of posts
social:

  - name: Weibo
    icon: weibo
    username: 大侠咕咚
    url: http://weibo.com/u/1874136301
    desc: Follow me on Weibo
    share: true

  - name: GitHub
    icon: github
    username: 咕咚
    url: https://github.com/maoruibin
    desc: Follow me on GitHub
    share: false

  - name: 知乎
    icon: zhihu
    username: 咕咚
    url: http://www.zhihu.com/people/maoruibin
    desc: Follow me on ZhiHu
    share: false

  - name: Google+
    icon: google-plus
    username: 瑞斌
    url: http://plus.google.com/107689066812933417058?rel=author
    desc: Add me to your Circles
    share: true

  - name: Twitter
    icon: twitter
    username: 咕咚
    url:
    desc: Add me to your Circles
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
